### ISSUE TITLE
How to set bin size for Human whole genome data?

### ISSUE THREAD

**Issue by KrithikaSubramanian** [abyzovlab/CNVpytor#102]
Hi,

Currently, I am working on Human whole genome sequencing data for finding CNVs. The human genome has above 30X coverage. As title, how to set bin size for ~30x human whole genome sequencing data?

Thanks in advance
Krithika S

**Comment by suvakov** [comment]
Depending on size of CNVs you are interested in. Minimal bin size is 100. Larger bin size reduce noise in RD and number of false positive calls, but events smaller than bin size will be missed. If you want to use BAF data as additional evidence, minimal bin size is around 5kbp due to density of SNPs. We suggest 10kbp or 100kbp.
