### ISSUE TITLE
What is the best protocol for calling CNV with WGS 30X data from multiple patients?

### ISSUE THREAD

**Issue by lgmgeo** [abyzovlab/CNVpytor#113]
Hi,

I'm working with Human WGS 30X data from multiple patients.

- First, I import read depth signal:
```
# Extracting RD signalfrom BAM
cnvpytor -root sample.pytor -rd sample.bam -chrom chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY chrMT
```
- Then I predict CNV regions:
```
# Calculating RD histograms for given bin size
cnvpytor -root sample.pytor -his 1000 10000 100000

# Segmentation using mean-shift technique
time cnvpytor -root sample.pytor -partition 1000 10000 100000

# print out calls to stdout
time cnvpytor -root sample.pytor -call 1000 10000 100000 >& sample.output
```

- Finally, I filter calls and I export CNV calls as VCFs:
I run the following csh script:
```
#!/bin/csh

# WARNING: Do not indent the code between "<<ENDL" and "ENDL"
foreach sample (sample)
        foreach binsize (1000 10000 100000)
                echo "...creation of ${sample}_cnvpythor_$binsize.vcf and ${sample}_cnvpythor_$binsize.filtered.vcf"
                cnvpytor -root $sample.pytor -view $binsize <<ENDL
set print_filename ${sample}_cnvpythor_$binsize.vcf
print calls
set Q0_range -1 0.5
set p_range 0 0.0001
set p_N 0 0.5
set print_filename ${sample}_cnvpythor_$binsize.filtered.vcf
print calls
ENDL
        end
end
```

My questions are: 
- What is the final aim of importing SNP data? 
Is it a specific step for calling **somatic** CNAs with joint caller (prototype)? 
Or is it useful to predict **germinal** CNV regions using joint caller (and so should I use it?)?

- Also, with 30X WGS, what are the recommended "bin sizes" to use? 
Only 1 bin_size or several bin_size?
Are "1000 10000 100000" sufficient? 
Or should I add "500"? Or just "500"?

- Should I use any other filters?

Thanks for any help you can provide me on this protocole,
Any advice is welcome,

Best,

Véronique

**Comment by arpanda** [comment]
**What is the final aim of importing SNP data?**

There are multiple reasons/aims for importing SNP data. Here I just listed few.
- To identify LOH events.
- Gives confidence to the CNV call
- Identify the false CNV calls.

**Is it a specific step for calling somatic CNAs with joint caller (prototype)?
Or is it useful to predict germinal CNV regions using joint caller (and so should I use it?)?**

Importing SNP and calculating BAF (-baf step) is required for prototype callers and it is not used at all for mean-shift (default) caller. However, it can be used for genotyping with -a option (link to example in Getting Started) and for plotting. This way one can get more confidence in CNV call.

**Also, with 30X WGS, what are the recommended "bin size" to use?
Are "1000 10000 100000" sufficient?
Or should I add "500"?**

- Depending on size of CNVs you are looking, it is always better to increase the bin size. This way noise is reduced. Minimal bin size for mean shift caller is 100.
- For BAF histograms and prototype callers minimal bin size should cover at least few SNPs. Due to typical SNP density we recommend 10kbp and 100kbp bins, ane we do not suggest bin size bellow 5kbp.

**Should I use any other filters?**
I think your filter criteria is fine.

Thanks 
Arijit

**Comment by lgmgeo** [comment]
Get it.
Thank you so much Arijit for this detailed answer!

**Comment by lgmgeo** [comment]
As a reminder from the CNVpytor publication (https://doi.org/10.1093/gigascience/giab074), if it can be useful to other users.
"The recommended minimal bin size, which depends on sequencing coverage, is provided in Supplementary Table S1".
![image](https://user-images.githubusercontent.com/49909073/167365145-394619f6-d3d7-4dd8-a0cc-2ee133f6daf5.png)

**Comment by dr-ashu-geno** [comment]
Dear @lgmgeo 

I've seen your comments in many issues on CNVpytor GitHub page, realizing you are using it on your data.

May I ask If you have any suggestions for methods to get a consensus set of CNVs that were called in all samples and do genotyping for the CNV call set in every sample? The number of samples in my study is high (around 12000). 

Thank you in advance,
Best,

**Comment by lgmgeo** [comment]
Dear @dr-ashu-geno ,

First, you need to call SV in your samples with different callers. 
In my opinion, the best way is to use different algorithms (read depth, split reads...). And indeed, CNVpytor is a really excellent tool from read depth ;o) 
Then, you need to merge SV across samples. For this, I suggest [Jasmine ](https://github.com/mkirsche/Jasmine/), but I haven't set any [definitive thresholds](https://github.com/mkirsche/Jasmine/issues/40) yet.

Of course, any comments from any user are welcome to complete this answer!

Best,
Véronique

**Comment by dr-ashu-geno** [comment]
Dear @lgmgeo 

Thank you so much for your quick reply.

I also tried using svimmer for getting the union of CNVs and now am doing genotyping using SVtyper.
So far so good.

Thanks again,
Best,

**Comment by lgmgeo** [comment]
**Genotyping**
Good to know for SVTyper, thanks. Nebula could be a good choice too.

**Merge**
I also tried svimmer, but (if I'm not mistaken) the positions (start, end) of the merged SVs correspond to the last of the merged SVs. And we do not have access to CIPOS and CIEND information.
