### ISSUE TITLE
Workflow for tumor-normal 

### ISSUE THREAD

**Issue by Indianhedgehog** [abyzovlab/CNVpytor#165]
Hi @arpanda,

I want to process tumor-normal samples, but I am unsure how to proceed.
I have been able to call the CNVs and filter them for the Tumor BAM files, but as I was reading more, I found that SNP data is required 
for identifying the LOH regions and for high-confidence calls. 
My Questions are:

1) Is the  variant vcf file sample specific i.e same sample snp-indel data? 
Is yes, how can i generate it? or is it the snp data that i can download from NCBI or 1000 genome project?

2) Is there any other method/workflow that you suggest for tumor-normal samples?  

Best
Rajesh

**Comment by arpanda** [comment]
CNVpytor can take VCF file as input for the SNP signal. Steps to process SNP signal is [here](https://github.com/abyzovlab/CNVpytor#importing-and-using-single-nucleotide-polymorphism-data ). You need to process your alignment file using a variant caller( example: GATK ) to identify snps and it should be sample specific. Otherwise information will not match. 

Your second query is not very clear to me. If you would like to process tumor-normal samples using CNVpytor for copy number analysis, you can process your input files separately first and then compare the calls.
