### ISSUE TITLE
exclude scaffolds

### ISSUE THREAD

**Issue by wbsimey** [abyzovlab/CNVpytor#195]
I am using CNVpyter for hundreds of low coverage genomes and I only want to analyze specified chromosomes. But, when I run
`cnvpytor -root Nbry_GG15_all.pytor -snp /home/bsimison/Projects/Neotoma/60_LC_5sp/Vcfs/Nf_ref/create/Nfusc_ref_60samp.vcf.gz -sample GG15 -chrom Chr1_nf Chr2_nf Chr3_nf Chr4_nf Chr5_nf Chr6_nf Chr7_nf Chr8_nf Chr9_nf Chr10_nf Chr11_nf Chr12_nf Chr13_nf Chr14_nf Chr15_nf Chr16_nf Chr17_nf Chr18_nf Chr19_nf Chr20_nf Chr21_nf Chr22_nf Chr23_nf Chr24_nf Chr25_nf Chr26_nf Chr27_nf ChrX_nf ChrY` it also analyzes the hundreds of scaffolds in each. For e.g. `bam file. INFO - Chromosome 'HiC_scaffold_30' read. Number of variants to store: 9991.`
How can I only include the chromosomes specified with the `-chrom` option?

**Comment by arpanda** [comment]
I assume, your input VCF file is not indexed. Because of that its reading the entire VCF. However, it's only storing only data for the specified chromosomes in the pytor. You can enable `-v d` to see the detailed log while processing.

You can alternatively verify this later by employing the -ls command.

- Arijit
