### ISSUE TITLE
Query Regarding CNV Estimation for Genes

### ISSUE THREAD

**Issue by OmonkeyGOD** [abyzovlab/CNVpytor#242]
Hi, 

Thank you for developing this useful package.

Recently, I used it to detect CNVs in my sample for genes of interest. I found that the estimated read depth for the entire merged region was quite different from that of my target gene (highlighted in red; see attached figure). The gene has a very high read depth, 5-7 times higher than the surrounding area. I also noticed a deletion/gap within 30 kb of this gene, which may have resulted in the filtration of this call. Is the estimated copy number for the merged region calculated as the average across the entire region? In this case, should I manually calculate the copy number of the gene to get a more accurate estimation?

Thanks!

![SampleRDplot](https://github.com/user-attachments/assets/770bbcbd-1911-484e-b988-2bef8d955ebc)

**Comment by arpanda** [comment]
Could you please clarify the `bin_size` used for the CNVpytor plot? Additionally, is this data based on WGS?

Using a larger `bin_size` can result in smaller CNV events being overlooked. In the current plot, three pieces of information are displayed in different colors:

 - Gray: Raw read depth signal
 - Black: GC-corrected read depth signal
 - Green: Copy number level

It appears that the highlighted peak is being smoothed out by the green line, likely because it spans too few bins. I suggest reducing the `bin_size` and regenerating the plot. If the green line adjusts accordingly, you can proceed with genotyping the affected gene to get the CNV level of the gene.

-Arijit

**Comment by OmonkeyGOD** [comment]
Hi Arijit,

Thank you so much for your response and the clarification. I used 1000bp bin size and my data are based on WGS. I will reduce the bin_size to 500 and 100 bp to see if the plot changes. Thanks!
