### ISSUE TITLE
Difficult to install gnureadline

### ISSUE THREAD

**Issue by lufuhao** [abyzovlab/CNVpytor#50]
It seems gnureadline (https://github.com/ludwigschwardt/python-gnureadline OR https://pypi.org/project/gnureadline/) is not well maintained. I found it difficult to install on ubuntu 20.04. Is there an alternative way to workaround this issue.

and in the requirement file, pathlib is duplicated

**Comment by suvakov** [comment]
Thank you for reporting. We will check is there an alternative library. Requirement file is fixed.

**Comment by m-rq** [comment]
I had the same issue. My operating system is Ubuntu 20.04.2 LTS. I cannot installed version 1.1 directly from Github, because of "gnureadline".
I solved this issue by following steps.
Firstly, I installed version 1.0 through Conda to make sure the dependencies are complete. Only version 1.0 is currently available in bioconda database.
`$conda install -c bioconda cnvpytor`
Secondly, I used "git clone" to download version 1.1 and then covered old version by run:
```
> git clone https://github.com/abyzovlab/CNVpytor.git
> cd CNVpytor
> pip3 install .
```
